/** @type {import('tailwindcss').Config} */
export default {
  content: ['./web/index.html', './web/src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'app-bg': 'var(--surface-app)',
        'app-canvas': 'var(--surface-app)',
        'app-sidebar': 'var(--surface-sidebar)',
        'app-panel': 'var(--surface-card)',
        'app-card': 'var(--surface-card)',
        'app-border': 'var(--border)',
        'app-text': 'var(--text-primary)',
        'app-muted': 'var(--text-tertiary)',
        'app-focus': 'var(--vt-yellow)',
        'app-strong': 'var(--text-primary)',
        'app-accent': 'var(--vt-yellow)',
        'app-accent-soft': 'var(--sidebar-item-active)',
        'app-accent-border': 'var(--vt-yellow-light)',
        'app-ink': 'var(--surface-ink)',
        'app-ink-soft': 'var(--surface-ink)',
        'app-on-ink': 'var(--text-on-dark)',
        'app-on-ink-muted': 'var(--text-on-dark-dim)',
        'brand-amber': '#f59e0b',
        'brand-terracotta': '#f59e0b',
        'status-green': 'var(--status-green)',
        'status-green-soft': 'var(--status-green-soft)',
        'status-amber': 'var(--status-amber)',
        'status-amber-soft': 'var(--status-amber-soft)',
        'status-red': 'var(--status-red)',
        'status-red-soft': 'var(--status-red-soft)',
        'status-blue': 'var(--status-blue)',
        'status-blue-soft': 'var(--status-blue-soft)',
        'status-purple': 'var(--status-purple)',
        'status-purple-soft': 'var(--status-purple-soft)',
      },
      boxShadow: {
        soft: '0 1px 3px rgba(46, 45, 57, 0.04)',
        'soft-lg': '0 4px 16px rgba(46, 45, 57, 0.08)',
        modal: '0 20px 48px rgba(46, 45, 57, 0.16)',
        'focus-accent': '0 0 0 3px rgba(255, 217, 25, 0.45)',
      },
      fontFamily: {
        sans: ['"Inter"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        display: ['"Montserrat"', '"Inter"', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
    },
  },
  plugins: [],
};
