-- ====================================================================
-- V.tal netWave - Oracle Database Baseline Migration
-- Prefixo Mandatório: NW_ para todas as tabelas
-- Nomenclatura: UPPER_SNAKE_CASE, PK_NW_*, FK_NW_*, UK_NW_*, IX_NW_*, CK_NW_*
-- Centralização direta no M&A (sem entidade intermediária de Campanha)
-- ====================================================================

-- 1. NW_MA (M&A Master)
CREATE TABLE NW_MA (
    ID VARCHAR2(36 CHAR) NOT NULL,
    NAME VARCHAR2(100 CHAR) NOT NULL,
    ORIGIN_PROVIDER VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(500 CHAR),
    START_DATE DATE NOT NULL,
    STATUS VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    UF VARCHAR2(2 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_NW_MA PRIMARY KEY (ID),
    CONSTRAINT CK_NW_MA_STATUS CHECK (STATUS IN ('ACTIVE', 'NEGOTIATION', 'PAUSED', 'COMPLETED', 'CANCELLED', 'ARCHIVED'))
);

-- 2. NW_TECHNICIAN (Técnicos Dedicados ao M&A)
CREATE TABLE NW_TECHNICIAN (
    ID VARCHAR2(36 CHAR) NOT NULL,
    MA_ID VARCHAR2(36 CHAR) NOT NULL,
    EXTERNAL_TECH_ID VARCHAR2(50 CHAR) NOT NULL,
    NAME VARCHAR2(100 CHAR) NOT NULL,
    VENDOR_COMPANY VARCHAR2(100 CHAR) NOT NULL,
    CITY VARCHAR2(100 CHAR) NOT NULL,
    UF VARCHAR2(2 CHAR) NOT NULL,
    DAILY_CAPACITY NUMBER(4) DEFAULT 8 NOT NULL,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    JOINED_AT DATE DEFAULT SYSDATE NOT NULL,
    LEFT_AT DATE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_NW_TECHNICIAN PRIMARY KEY (ID),
    CONSTRAINT FK_NW_TECH_MA FOREIGN KEY (MA_ID) REFERENCES NW_MA(ID),
    CONSTRAINT UK_NW_TECH_MA UNIQUE (MA_ID, EXTERNAL_TECH_ID),
    CONSTRAINT CK_NW_TECH_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);
CREATE INDEX IX_NW_TECH_MA ON NW_TECHNICIAN(MA_ID);

-- 3. NW_MIGRATION_LOT (Lotes de Importação por M&A)
CREATE TABLE NW_MIGRATION_LOT (
    ID VARCHAR2(36 CHAR) NOT NULL,
    MA_ID VARCHAR2(36 CHAR) NOT NULL,
    FILE_NAME VARCHAR2(255 CHAR) NOT NULL,
    TOTAL_RECORDS NUMBER(10) DEFAULT 0 NOT NULL,
    VALID_RECORDS NUMBER(10) DEFAULT 0 NOT NULL,
    REJECTED_RECORDS NUMBER(10) DEFAULT 0 NOT NULL,
    DUPLICATE_RECORDS NUMBER(10) DEFAULT 0 NOT NULL,
    IMPORT_STATUS VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
    IMPORTED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_NW_MIGRATION_LOT PRIMARY KEY (ID),
    CONSTRAINT FK_NW_LOT_MA FOREIGN KEY (MA_ID) REFERENCES NW_MA(ID),
    CONSTRAINT CK_NW_LOT_STATUS CHECK (IMPORT_STATUS IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);
CREATE INDEX IX_NW_LOT_MA ON NW_MIGRATION_LOT(MA_ID);

-- 4. NW_OS_BATCH (Lotes de Comando Massivo de Abertura de OS)
CREATE TABLE NW_OS_BATCH (
    ID VARCHAR2(36 CHAR) NOT NULL,
    MA_ID VARCHAR2(36 CHAR) NOT NULL,
    TOTAL_CUSTOMERS NUMBER(10) DEFAULT 0 NOT NULL,
    SUCCESS_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    FAILED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_NW_OS_BATCH PRIMARY KEY (ID),
    CONSTRAINT FK_NW_OS_BATCH_MA FOREIGN KEY (MA_ID) REFERENCES NW_MA(ID),
    CONSTRAINT CK_NW_OS_BATCH_STATUS CHECK (STATUS IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);
CREATE INDEX IX_NW_OS_BATCH_MA ON NW_OS_BATCH(MA_ID);

-- 5. NW_MIGRATION_ITEM (Entidade Central da Jornada Individual 1:1:1)
CREATE TABLE NW_MIGRATION_ITEM (
    ID VARCHAR2(36 CHAR) NOT NULL,
    MA_ID VARCHAR2(36 CHAR) NOT NULL,
    LOT_ID VARCHAR2(36 CHAR) NOT NULL,
    BATCH_ID VARCHAR2(36 CHAR),
    
    -- Dados de Identificação do Cliente
    CUSTOMER_ID VARCHAR2(100 CHAR) NOT NULL,
    EXTERNAL_CUSTOMER_ID VARCHAR2(100 CHAR) NOT NULL,
    SUBSCRIPTION_ID VARCHAR2(100 CHAR) NOT NULL,
    CUSTOMER_NAME VARCHAR2(200 CHAR) NOT NULL,
    
    -- Endereço e Viabilidade
    RAW_ADDRESS VARCHAR2(500 CHAR) NOT NULL,
    CEP VARCHAR2(10 CHAR) NOT NULL,
    STREET VARCHAR2(200 CHAR),
    STREET_NR VARCHAR2(30 CHAR),
    COMPLEMENT VARCHAR2(100 CHAR),
    NEIGHBORHOOD VARCHAR2(100 CHAR),
    CITY VARCHAR2(100 CHAR) NOT NULL,
    STATE_OR_UF VARCHAR2(2 CHAR) NOT NULL,
    GEOGRAPHIC_ADDRESS_ID VARCHAR2(50 CHAR),
    ADDRESS_MATCH_SCORE NUMBER(5,2),
    VIABILITY_ID VARCHAR2(50 CHAR),
    VIABILITY_STATUS VARCHAR2(50 CHAR),
    
    -- Infraestrutura de Origem
    ORIGIN_PROVIDER VARCHAR2(100 CHAR) NOT NULL,
    ORIGIN_ACCESS_ID VARCHAR2(100 CHAR),
    ORIGIN_BOX_ID VARCHAR2(100 CHAR) NOT NULL,
    
    -- Infraestrutura Alvo V.tal
    TARGET_INVENTORY_ID VARCHAR2(50 CHAR),
    TARGET_HC_ID VARCHAR2(50 CHAR),
    TARGET_BOX_ID VARCHAR2(50 CHAR),
    TARGET_BOX_TYPE VARCHAR2(20 CHAR),
    
    -- Rastreabilidade de Serial de ONT (Duplo Serial)
    ONT_SERIAL_ORIGINAL VARCHAR2(50 CHAR) NOT NULL,
    ONT_SERIAL_EFFECTIVE VARCHAR2(50 CHAR) NOT NULL,
    
    -- Ordens Operacionais (1 Cliente = 1 OS = 1 SA)
    CRM_ORDER_ID VARCHAR2(50 CHAR),
    OS_ID VARCHAR2(50 CHAR),
    SA_ID VARCHAR2(50 CHAR),
    OS_CREATION_STATUS VARCHAR2(30 CHAR),
    SA_CREATION_STATUS VARCHAR2(30 CHAR),
    
    -- Estado da Jornada
    MIGRATION_STATUS VARCHAR2(40 CHAR) DEFAULT 'IMPORTED' NOT NULL,
    
    -- Programação de Campo (SA desatribuída até agendamento)
    SCHEDULED_DATE DATE,
    TECHNICIAN_ID VARCHAR2(50 CHAR),
    
    -- Erros e Diagnóstico
    ERROR_STAGE VARCHAR2(50 CHAR),
    ERROR_CODE VARCHAR2(50 CHAR),
    ERROR_DESCRIPTION VARCHAR2(1000 CHAR),
    
    -- Timestamps de Auditoria
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PREPARED_AT TIMESTAMP(6) WITH TIME ZONE,
    SCHEDULED_AT TIMESTAMP(6) WITH TIME ZONE,
    MIGRATED_AT TIMESTAMP(6) WITH TIME ZONE,
    
    CONSTRAINT PK_NW_MIGRATION_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_NW_ITEM_MA FOREIGN KEY (MA_ID) REFERENCES NW_MA(ID),
    CONSTRAINT FK_NW_ITEM_LOT FOREIGN KEY (LOT_ID) REFERENCES NW_MIGRATION_LOT(ID),
    CONSTRAINT FK_NW_ITEM_BATCH FOREIGN KEY (BATCH_ID) REFERENCES NW_OS_BATCH(ID),
    CONSTRAINT UK_NW_ITEM_CUST_MA UNIQUE (MA_ID, EXTERNAL_CUSTOMER_ID)
);

CREATE INDEX IX_NW_ITEM_STATUS ON NW_MIGRATION_ITEM(MIGRATION_STATUS);
CREATE INDEX IX_NW_ITEM_MA_STATUS ON NW_MIGRATION_ITEM(MA_ID, MIGRATION_STATUS);
CREATE INDEX IX_NW_ITEM_ORIGIN_BOX ON NW_MIGRATION_ITEM(ORIGIN_BOX_ID);
CREATE INDEX IX_NW_ITEM_TARGET_BOX ON NW_MIGRATION_ITEM(TARGET_BOX_ID);
CREATE INDEX IX_NW_ITEM_OS ON NW_MIGRATION_ITEM(OS_ID);
CREATE INDEX IX_NW_ITEM_SA ON NW_MIGRATION_ITEM(SA_ID);
CREATE INDEX IX_NW_ITEM_TECH_DATE ON NW_MIGRATION_ITEM(TECHNICIAN_ID, SCHEDULED_DATE);

-- 6. NW_BOX_SCHEDULE (Programação de Campo por CDO/CDOI)
CREATE TABLE NW_BOX_SCHEDULE (
    ID VARCHAR2(36 CHAR) NOT NULL,
    MA_ID VARCHAR2(36 CHAR) NOT NULL,
    TARGET_BOX_ID VARCHAR2(50 CHAR) NOT NULL,
    TARGET_BOX_TYPE VARCHAR2(20 CHAR) DEFAULT 'CDO' NOT NULL,
    MUNICIPALITY VARCHAR2(100 CHAR),
    NEIGHBORHOOD VARCHAR2(100 CHAR),
    TOTAL_CUSTOMERS NUMBER(6) DEFAULT 0 NOT NULL,
    TOTAL_ORDERS NUMBER(6) DEFAULT 0 NOT NULL,
    SCHEDULE_STATUS VARCHAR2(30 CHAR) DEFAULT 'AVAILABLE' NOT NULL,
    SCHEDULED_DATE DATE,
    TECHNICIAN_ID VARCHAR2(50 CHAR),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    CONSTRAINT PK_NW_BOX_SCHEDULE PRIMARY KEY (ID),
    CONSTRAINT FK_NW_SCHED_MA FOREIGN KEY (MA_ID) REFERENCES NW_MA(ID),
    CONSTRAINT UK_NW_SCHED_BOX_MA UNIQUE (MA_ID, TARGET_BOX_ID),
    CONSTRAINT CK_NW_SCHED_STATUS CHECK (SCHEDULE_STATUS IN ('AVAILABLE', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED'))
);
CREATE INDEX IX_NW_SCHED_DATE ON NW_BOX_SCHEDULE(SCHEDULED_DATE);
CREATE INDEX IX_NW_SCHED_TECH ON NW_BOX_SCHEDULE(TECHNICIAN_ID);

-- 7. NW_BOX_SCHEDULE_HISTORY (Auditoria de Reprogramação)
CREATE TABLE NW_BOX_SCHEDULE_HISTORY (
    ID VARCHAR2(36 CHAR) NOT NULL,
    SCHEDULE_ID VARCHAR2(36 CHAR) NOT NULL,
    OLD_DATE DATE,
    NEW_DATE DATE NOT NULL,
    OLD_TECHNICIAN_ID VARCHAR2(50 CHAR),
    NEW_TECHNICIAN_ID VARCHAR2(50 CHAR) NOT NULL,
    REASON VARCHAR2(255 CHAR),
    CHANGED_BY VARCHAR2(100 CHAR) NOT NULL,
    CHANGED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_NW_SCHED_HIST PRIMARY KEY (ID),
    CONSTRAINT FK_NW_HIST_SCHED FOREIGN KEY (SCHEDULE_ID) REFERENCES NW_BOX_SCHEDULE(ID)
);
CREATE INDEX IX_NW_HIST_SCHED ON NW_BOX_SCHEDULE_HISTORY(SCHEDULE_ID);

-- 8. NW_SERIAL_CHANGE (Trilha de Auditoria de Correção de Serial ONT)
CREATE TABLE NW_SERIAL_CHANGE (
    ID VARCHAR2(36 CHAR) NOT NULL,
    ITEM_ID VARCHAR2(36 CHAR) NOT NULL,
    ORIGINAL_SERIAL VARCHAR2(50 CHAR) NOT NULL,
    NEW_SERIAL VARCHAR2(50 CHAR) NOT NULL,
    REASON VARCHAR2(50 CHAR) NOT NULL,
    OBSERVATION VARCHAR2(500 CHAR),
    CHANGED_BY VARCHAR2(100 CHAR) NOT NULL,
    CHANGED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_NW_SERIAL_CHANGE PRIMARY KEY (ID),
    CONSTRAINT FK_NW_SER_ITEM FOREIGN KEY (ITEM_ID) REFERENCES NW_MIGRATION_ITEM(ID),
    CONSTRAINT CK_NW_SER_REASON CHECK (REASON IN ('SOURCE_DATA_MISMATCH', 'PREVIOUS_ONT_REPLACEMENT', 'IMPORT_DATA_ERROR', 'OTHER'))
);
CREATE INDEX IX_NW_SER_ITEM ON NW_SERIAL_CHANGE(ITEM_ID);

-- 9. NW_CUTOVER_BATCH (Lotes de Cutover)
CREATE TABLE NW_CUTOVER_BATCH (
    ID VARCHAR2(36 CHAR) NOT NULL,
    MA_ID VARCHAR2(36 CHAR) NOT NULL,
    TARGET_BOX_ID VARCHAR2(50 CHAR),
    TOTAL_ITEMS NUMBER(10) DEFAULT 0 NOT NULL,
    SUCCESS_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    FAILED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
    EXECUTED_BY VARCHAR2(100 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_NW_CUTOVER_BATCH PRIMARY KEY (ID),
    CONSTRAINT FK_NW_CUT_MA FOREIGN KEY (MA_ID) REFERENCES NW_MA(ID),
    CONSTRAINT CK_NW_CUT_STATUS CHECK (STATUS IN ('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIALLY_FAILED', 'FAILED'))
);
CREATE INDEX IX_NW_CUT_MA ON NW_CUTOVER_BATCH(MA_ID);

-- 10. NW_CUTOVER_ITEM (Execução Individual em 13 Etapas)
CREATE TABLE NW_CUTOVER_ITEM (
    ID VARCHAR2(36 CHAR) NOT NULL,
    CUTOVER_BATCH_ID VARCHAR2(36 CHAR) NOT NULL,
    ITEM_ID VARCHAR2(36 CHAR) NOT NULL,
    EXECUTION_STAGE VARCHAR2(50 CHAR) NOT NULL,
    STATUS VARCHAR2(20 CHAR) NOT NULL,
    DISCOVERY_STATUS VARCHAR2(50 CHAR),
    OPTICAL_POWER_RX NUMBER(6,2),
    OPTICAL_POWER_TX NUMBER(6,2),
    DIAGNOSTICS_RESULT VARCHAR2(500 CHAR),
    ERROR_CODE VARCHAR2(50 CHAR),
    ERROR_DESCRIPTION VARCHAR2(500 CHAR),
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_NW_CUTOVER_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_NW_CUT_ITEM_BATCH FOREIGN KEY (CUTOVER_BATCH_ID) REFERENCES NW_CUTOVER_BATCH(ID),
    CONSTRAINT FK_NW_CUT_ITEM_MIG FOREIGN KEY (ITEM_ID) REFERENCES NW_MIGRATION_ITEM(ID),
    CONSTRAINT CK_NW_CUT_ITEM_STATUS CHECK (STATUS IN ('IN_PROGRESS', 'SUCCESS', 'FAILED'))
);
CREATE INDEX IX_NW_CUT_ITEM_MIG ON NW_CUTOVER_ITEM(ITEM_ID);

-- 11. NW_ROLLBACK (Trilha de Reversão para Rede de Origem)
CREATE TABLE NW_ROLLBACK (
    ID VARCHAR2(36 CHAR) NOT NULL,
    ITEM_ID VARCHAR2(36 CHAR) NOT NULL,
    ORIGIN_BOX_ID VARCHAR2(100 CHAR) NOT NULL,
    REASON VARCHAR2(500 CHAR) NOT NULL,
    STATUS VARCHAR2(30 CHAR) DEFAULT 'ROLLBACK_REQUESTED' NOT NULL,
    REQUESTED_BY VARCHAR2(100 CHAR) NOT NULL,
    REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_NW_ROLLBACK PRIMARY KEY (ID),
    CONSTRAINT FK_NW_RB_ITEM FOREIGN KEY (ITEM_ID) REFERENCES NW_MIGRATION_ITEM(ID),
    CONSTRAINT CK_NW_RB_STATUS CHECK (STATUS IN ('ROLLBACK_REQUESTED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK'))
);
CREATE INDEX IX_NW_RB_ITEM ON NW_ROLLBACK(ITEM_ID);
CREATE INDEX IX_NW_RB_ORIGIN_BOX ON NW_ROLLBACK(ORIGIN_BOX_ID);

-- 12. NW_AUDIT_LOG (Trilha de Auditoria com Correlation ID)
CREATE TABLE NW_AUDIT_LOG (
    ID VARCHAR2(36 CHAR) NOT NULL,
    CORRELATION_ID VARCHAR2(50 CHAR) NOT NULL,
    ACTOR VARCHAR2(100 CHAR) NOT NULL,
    ACTION VARCHAR2(100 CHAR) NOT NULL,
    ENTITY_TYPE VARCHAR2(50 CHAR) NOT NULL,
    ENTITY_ID VARCHAR2(50 CHAR) NOT NULL,
    BEFORE_STATE CLOB,
    AFTER_STATE CLOB,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_NW_AUDIT_LOG PRIMARY KEY (ID)
);
CREATE INDEX IX_NW_AUDIT_CORR ON NW_AUDIT_LOG(CORRELATION_ID);
CREATE INDEX IX_NW_AUDIT_ENTITY ON NW_AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IX_NW_AUDIT_ACTION ON NW_AUDIT_LOG(ACTION);
