-- ====================================================================
-- V.tal netWave - Oracle Query Views and Specialized Indexes
-- ====================================================================

-- Visão consolidada para Liberação de Caixas de Origem (Decommissioning por M&A)
CREATE OR REPLACE VIEW NW_VW_ORIGIN_BOX_RELEASE AS
SELECT 
    i.ORIGIN_BOX_ID,
    i.ORIGIN_PROVIDER,
    i.MA_ID,
    COUNT(i.ID) AS TOTAL_CUSTOMERS,
    SUM(CASE WHEN i.MIGRATION_STATUS = 'MIGRATED' THEN 1 ELSE 0 END) AS MIGRATED_CUSTOMERS,
    SUM(CASE WHEN i.MIGRATION_STATUS NOT IN ('MIGRATED', 'ROLLED_BACK', 'ROLLBACK_REQUESTED', 'ROLLBACK_IN_PROGRESS') THEN 1 ELSE 0 END) AS PENDING_CUSTOMERS,
    SUM(CASE WHEN i.MIGRATION_STATUS IN ('ROLLED_BACK', 'ROLLBACK_REQUESTED', 'ROLLBACK_IN_PROGRESS') THEN 1 ELSE 0 END) AS ROLLBACK_CUSTOMERS,
    CASE 
        WHEN SUM(CASE WHEN i.MIGRATION_STATUS IN ('ROLLED_BACK', 'ROLLBACK_REQUESTED', 'ROLLBACK_IN_PROGRESS') THEN 1 ELSE 0 END) > 0 THEN 'BLOCKED_BY_ROLLBACK'
        WHEN SUM(CASE WHEN i.MIGRATION_STATUS = 'MIGRATED' THEN 1 ELSE 0 END) = COUNT(i.ID) THEN 'READY_FOR_RELEASE'
        WHEN SUM(CASE WHEN i.MIGRATION_STATUS = 'MIGRATED' THEN 1 ELSE 0 END) > 0 THEN 'PARTIALLY_MIGRATED'
        ELSE 'NOT_READY'
    END AS RELEASE_STATUS
FROM NW_MIGRATION_ITEM i
GROUP BY i.ORIGIN_BOX_ID, i.ORIGIN_PROVIDER, i.MA_ID;

-- Visão consolidada para o Funil de Migração por M&A
CREATE OR REPLACE VIEW NW_VW_MIGRATION_FUNNEL AS
SELECT 
    MA_ID,
    COUNT(ID) AS TOTAL_IMPORTED,
    SUM(CASE WHEN MIGRATION_STATUS NOT IN ('IMPORTED', 'PREPARING', 'ADDRESS_EXCEPTION') THEN 1 ELSE 0 END) AS TOTAL_SANITIZED,
    SUM(CASE WHEN MIGRATION_STATUS NOT IN ('IMPORTED', 'PREPARING', 'ADDRESS_EXCEPTION', 'NOT_VIABLE') THEN 1 ELSE 0 END) AS TOTAL_VIABLE,
    SUM(CASE WHEN MIGRATION_STATUS IN ('OS_CREATED', 'SCHEDULED', 'IN_FIELD', 'ACTIVATING', 'MIGRATED') THEN 1 ELSE 0 END) AS TOTAL_OS_CREATED,
    SUM(CASE WHEN MIGRATION_STATUS IN ('SCHEDULED') THEN 1 ELSE 0 END) AS TOTAL_SCHEDULED,
    SUM(CASE WHEN MIGRATION_STATUS IN ('IN_FIELD', 'ACTIVATING') THEN 1 ELSE 0 END) AS TOTAL_IN_FIELD,
    SUM(CASE WHEN MIGRATION_STATUS = 'MIGRATED' THEN 1 ELSE 0 END) AS TOTAL_MIGRATED,
    SUM(CASE WHEN MIGRATION_STATUS IN ('MIGRATION_FAILED', 'SERIAL_EXCEPTION', 'ADDRESS_EXCEPTION', 'NOT_VIABLE') THEN 1 ELSE 0 END) AS TOTAL_EXCEPTIONS,
    SUM(CASE WHEN MIGRATION_STATUS IN ('ROLLBACK_REQUESTED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK') THEN 1 ELSE 0 END) AS TOTAL_ROLLBACKS
FROM NW_MIGRATION_ITEM
GROUP BY MA_ID;
